<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
    xmlns:html="http://www.w3.org/TR/REC-html40"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:video="http://www.google.com/schemas/sitemap-video/1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Video Sitemap</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<style type="text/css">
			body {
				background: #f9fcfe;
				color: #000;
				margin: 0;
				padding: 0;
			}
			
			#wrap {
				background: #fff;
				border: 1px solid #ccc;
				clear: both;
				margin: 15px 5%;
				padding: 1em;
			}
			
			h1 {
				font-family: Georgia, "Times New Roman", Times, serif;
				font-size: 32px;
				font-weight: normal;
				background: url('wp-admin/images/heading-bg.gif') repeat-x bottom;
				margin: 0;
			}
			
			#about {
				padding: 8px;
				margin: 10px;
			}
			
			table {
				display: block;
				overflow-x: auto;
			}
			
			thead {
				background: #dfdfdf;
			}
			
			td {
				padding: 8px;
			}
			
			th {
				background-color: #ddd;
				text-align: left;
				padding: 6px;
				font-size: 13px;
			}
			
			tr.odd {
				background-color: #f1f1f1;
			}
			
			tfoot p {
				margin: 0;
				padding: 10px 0 0;
				text-align: center;
			}
			
			body, td {
				font: 13px "Lucida Grande", "Lucida Sans Unicode", Tahoma, Verdana, sans-serif;
			}
			
			a {
				border-bottom: 1px solid #69c;
				color: #00019b;
				text-decoration: none;
			}
			
			a:visited {
				color: #004;
			}

			a:hover {
				color: #069;
			}
		</style>
	</head>
	<body>
		<div id="wrap">
			<h1>Video Sitemap</h1>
			<div id="about">
				<p>Generated by <a href="http://www.channel-ai.com/blog/plugins/flv-embed/" title="FLV Embed Plugin for WordPress">FLV Embed Plugin</a> for <a href="http://wordpress.org/">WordPress</a></p>
				<p>More information about video sitemap can be found on <a href="http://www.google.com/support/webmasters/bin/topic.py?topic=10079">Google</a></p>
			</div>
			
			<div id="content">
				<table>
				<thead>
					<tr>
						<th>FLV</th>
						<th>Title</th>
						<th>Landing Page</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td colspan="3">
							<p>Powered by <a href="http://www.channel-ai.com/blog/plugins/flv-embed/" title="FLV Embed Plugin for WordPress">FLV Embed Plugin for WordPress</a></p>
						</td>
					</tr>
				</tfoot>
				<tbody>
					<xsl:for-each select="sitemap:urlset/sitemap:url">
						<tr>
							<xsl:if test="position() mod 2 = 1">
								<xsl:attribute  name="class">odd</xsl:attribute>
							</xsl:if>

							<td>
								<xsl:variable name="flvURL">
									<xsl:value-of select="video:video/video:player_loc"/>
								</xsl:variable>
								<a href="{$flvURL}">
									<xsl:value-of select="video:video/video:content_loc"/>
								</a>
							</td>
							
							<td>
								<xsl:value-of select="video:video/video:title"/>
							</td>
							
							<td>
								<xsl:variable name="itemURL">
									<xsl:value-of select="sitemap:loc"/>
								</xsl:variable>
								<a href="{$itemURL}">
									<xsl:value-of select="sitemap:loc"/>
								</a>
							</td>
						</tr>
					</xsl:for-each>
					</tbody>
				</table>
			</div>
			
			<div id="footer"></div>
		</div>
	</body>
</html>
</xsl:template>

</xsl:stylesheet>
